### ISSUE TITLE
[Debian Sid] CMake does not detect libmng

### ISSUE THREAD

**Issue by JORGETECH** [heliocastro/kde2#3]
Trying to run cmake gives me the following error even though all libmng libraries (32 and 64 bit) are installed through the Debian repos.

`-- Checking for one of the modules 'libmng'
CMake Error at /usr/share/cmake-3.9/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'libmng' found
Call Stack (most recent call first):
  qt2/CMakeLists.txt:57 (pkg_search_module)`

`-- Checking for one of the modules 'libmng'
CMake Error at /usr/share/cmake-3.9/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'libmng' found
Call Stack (most recent call first):
  kdelibs/CMakeLists.txt:60 (pkg_search_module)`

Excluding libmng is not possible since several qt2 and kdelibs components use it.

Any ideas?

**Comment by heliocastro** [comment]
Hi. Happy new year and I'm on travel to celebrate the passage. Probably you're missing the package libmng-dev. If this not fixing, leave a message and I will help to fix it when I back from Holliday's

**Comment by JORGETECH** [comment]
The same happens with the libmng-dev package installed. Happy new year and have a nice travel!

**Comment by heliocastro** [comment]
Moin Moin 

So i just fixed detection ( or not ) of libmng on distros that not provide pkgconfig or not provide libmng at all.
Are you able to test on your side ? I tested on debian unstable here.

**Comment by JORGETECH** [comment]
I'll test it and report back.

**Comment by JORGETECH** [comment]
I cloned again the repo but the problem seems to be still present. I installed both libmng-dev and libmng1 64 and 32-bit versions. I am also running Debian unstable, what packages did you install to build it? I don't know if I am missing something.

**Comment by JORGETECH** [comment]
I tried again but this time cloning the repos separately (the ones in the kde2 repo point to older commits) and at least I got Qt2 to work. I also got kdelibs to find libmng after applying the same fix to CMakeLists.txt. I would contribute that change myself but I still need to learn on how to do that kind of things on GitHub, it should be really simple to change since it's the same as qt2.
